### ISSUE TITLE
'HubApi' object has no attribute 'hub_client'

### ISSUE THREAD

**Issue by IgorFlint** [deeplearninc/auger-ai#8] opened 2019-06-20 00:10 UTC
Trying to deploy model locally got:
```
(auger-ai) [03:09] flint@flint-desktop:~/projects/deeplearninc/auger-ai/igor_iris_augerai$ augerai model deploy 05A611073214408 --locally
Downloading model 05A611073214408
'HubApi' object has no attribute 'hub_client'
```

**Comment by vlad-dplrn** [comment] 2019-07-19 13:05
Can't reproduce, closing for now

**Closed by vlad-dplrn** 2019-07-19 13:05 UTC
Labels: bug
